//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatIf.Database {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhatIf.Database.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///		Id,
        ///		JoinId,
        ///		[Name],
        ///		LeaderId,
        ///		[Started],
        ///		Ended
        ///FROM
        ///		[Session]
        ///WHERE
        ///		JoinId = @JoinId AND
        ///		[Started] = 0 AND
        ///		Ended = 0.
        /// </summary>
        internal static string FindSessionByJoinId {
            get {
                return ResourceManager.GetString("FindSessionByJoinId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///		Id,
        ///		SessionId,
        ///		Nickname
        ///FROM
        ///		[User]
        ///WHERE
        ///		Id = @Id.
        /// </summary>
        internal static string FindUser {
            get {
                return ResourceManager.GetString("FindUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///		Id,
        ///		SessionId,
        ///		Nickname
        ///FROM
        ///		[User]
        ///WHERE
        ///		SessionId = @SessionId.
        /// </summary>
        internal static string FindUsersInSession {
            get {
                return ResourceManager.GetString("FindUsersInSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO
        ///		[Session]
        ///		(
        ///			Id,
        ///			JoinId,
        ///			[Name],
        ///			LeaderId,
        ///			[Started],
        ///			Ended
        ///		)
        ///VALUES
        ///		
        ///		(
        ///			@Id,
        ///			@JoinId,
        ///			@Name,
        ///			@LeaderId,
        ///			@Started,
        ///			@Ended
        ///		).
        /// </summary>
        internal static string InsertSession {
            get {
                return ResourceManager.GetString("InsertSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO
        ///		[User]
        ///		(
        ///			Id,
        ///			SessionId,
        ///			Nickname			
        ///		)
        ///VALUES
        ///		
        ///		(
        ///			@Id,
        ///			@SessionId,
        ///			@Nickname
        ///		).
        /// </summary>
        internal static string InsertUser {
            get {
                return ResourceManager.GetString("InsertUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE
        ///		[Session]
        ///SET
        ///		LeaderId = @UserId
        ///WHERE
        ///		Id = @SessionId.
        /// </summary>
        internal static string UpdateSessionLeader {
            get {
                return ResourceManager.GetString("UpdateSessionLeader", resourceCulture);
            }
        }
    }
}
